"""empty message

Revision ID: e245842a458d
Revises: a2bc5e07acd9
Create Date: 2024-08-09 22:49:17.023213

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e245842a458d'
down_revision: Union[str, None] = 'a2bc5e07acd9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('uesrs', sa.Column('discription', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('uesrs', 'discription')
    # ### end Alembic commands ###
