"""empty message

Revision ID: ffd125073f1c
Revises: e245842a458d
Create Date: 2024-08-09 22:50:07.106097

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ffd125073f1c'
down_revision: Union[str, None] = 'e245842a458d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('uesrs', 'discription',
               existing_type=sa.TEXT(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('uesrs', 'discription',
               existing_type=sa.TEXT(),
               nullable=True)
    # ### end Alembic commands ###
